import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Shu-katsu",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <body style={{ margin: 0, fontFamily: "sans-serif" }}>{children}</body>
    </html>
  );
}
